apiVersion: apps/v1
kind: Deployment
metadata:
  name: expressjs-hs
  labels:
    name: expressjs-hs
spec:
  replicas: 3
  selector:
    matchLabels:
      name: expressjs-hs
  template:
    metadata:
      name: expressjs-hs
      labels:
        name: expressjs-hs
    spec:
      containers:
        - name: expressjs-hs
          image: herysepty/expressjs:v1
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: expressjs-service
spec:
  type: NodePort
  selector:
    name: expressjs-hs
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
