apiVersion: apps/v1
kind: Deployment
metadata:
  name: expressjs-hs
  # namespace: app-service
  labels:
    name: expressjs-hs
spec:
  selector:
    matchLabels:
      name: expressjs-hs
  template:
    metadata:
      name: expressjs-hs
      labels:
        name: expressjs-hs
    spec:
      containers:
        - name: expressjs-hs
          image: herysepty/expressjs:v1
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
        - name: expressjs-hs-v2
          image: herysepty/expressjs:v5
          ports:
            - containerPort: 3002
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: expressjs-service
  # namespace: app-service
spec:
  type: NodePort
  selector:
    name: expressjs-hs
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
      name: expressjs-hs
      protocol: TCP
    - port: 3002
      targetPort: 3002
      nodePort: 30002
      name: expressjs-hs-v2
      protocol: TCP
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: expressjs-service-v2
#   # namespace: app-service
# spec:
#   type: NodePort
#   selector:
#     name: expressjs-hs
#   ports:
#     - port: 30002
#       targetPort: 3002
#       nodePort: 30002
#       name: expressjs-hs-v2
#       protocol: TCP
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-expressjs-hs
  # namespace: app-service
spec:
  minReplicas: 1
  maxReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: expressjs-hs
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    # - type: Resource
    #   resource:
    #     name: memory
    #     target:
    #       type: Utilization
    #       averageUtilization: 20
